env:
  global:
    secure: S/sPmc5FGP5WNQKHBFro7XFnt89yrVj0tNOf2zWm7kYeOsEFSyicTn7mYDgY34HBrTh1I0t1dQpq6mE6WFJrXHU2fwfEnBtZDcv8k4PrM6XqBKSVe7A1yRV2PFSngoEyV9IDraILaVuJFynSzn9AVi55IyWc3VULGMxU1WJGrXbEU+hEcVj7SiFMjqdlZZTToBbm8Ig4zG3OJl5LEvW7q92SBLZKJj0ctYtdegec52EOnBhALgRCvqdUhBjyOOTKMsbIGWbGOxY1/rVjsQiCBXI545UFVJ7NzlDZqF5CF5mfm6blZAaFY7Me0MKhsJpbkwW9+TBdRKQ7sfMYYwM1/MlMaRE56ceGUrJPufsqnXZK8h/tX2+Xsq42V6OWVys8607cUOCzaGOt3jfgca3RD2gyv19MSbJLxVQkDIAh+gJn9Vf55owb8tgJzGe87EULv+gvI8zC4dvuegGaIQG0e5lu6KaeFl09DcDsCajIhIc4Em7bT0lJKVZD40cadnf/2XKW/2b9wz09wJcMkrT7BmE5iQFt9GvCMtcJIgi+Om/92JdJOP9nDAR0NnTwPSMocdVxzgxxB5TXLP8CUdUlskyq2nbtxPNF5kWVa9LO1+pCPohevSk0D4loEq7RINf8L8SAd/QVL9qYEY7WqvhiI2+8KNtoOyOqY1ZGMEXAC0k=

matrix:
  include:
    - name: Android Build
      language: android
      jdk: openjdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_script:
        - echo $decryption_password
        - echo $decryption_password | gpg --passphrase-fd 0 secrets.tar.gpg
        - tar xvf secrets.tar
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - gem install bundler && cd android && bundle install && cd ..
      script:
        - flutter packages get
        - flutter test
        - flutter build apk
        - cd android && bundle exec fastlane build_android && bundle exec fastlane deploy_android
