env:
  global:
    secure: "va0vZPvQqfLorTY8VRa0zZKelaX8Z38gPp2CKNQ+At64b1cvoPBsQ0VoSy4kUdRBBUo8/RB9/OeiNedPTDCR51oaGfOevecdyvdEiZid+69t5KEpNT6VKMauOj2UJ28JyMATvG0HxqRDY+5r0Ia16ftO1gDIMlvwSG0KzVPJC8ol47by2uPEZAT8SE3ccHK42vLM0l8pmuK3mckzij++W+qe47rJ2r3LlWvn2xq39L4yWmOuME0roCdS6hl/5LDqug+nD5gOcuZ+v+RfirLTi2JXkYGMuZ/dsalLhxXCiQZVCJhPu6D6eI4sFQX11PwmIVJ8Lr/HLOPquKOqABmzcyWjkb5l8MTt/DtQUXNZjRepAj53gHH1BQZxNijthEuwzwik3kfBLIYrQW1gHXCaUFJSBrL7a0UapI0LMOYLXbybJllvZFn5fTSLaZqeEHxHCmwP6kXmuVHx9Hc8Iik5SphLdOXwlFzac9duHA7+G/WY9rI2eGpo2lb1zj6fshOW3jtSu2iA8nav7p1Vu75eYim5y+wNuAJPrlbHlImV7sarnleIZoEnEgAdLOgjjnYN0MaLvIFMcL6tYWnzxqsYsYxKYDBkpSH9bPvyqNd465m4LNP0/UL2nPblNa0RF6gn7BhVTYufkkc7Zq1+A1Of9uHVdHlBbEfUTvq1hsYLRRc="

matrix:
  include:
    - name: Android Build
      language: android
      jdk: openjdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_script:
        - echo $decryption_password | gpg --passphrase-fd 0 secrets.tar.gpg
        - tar xvf secrets.tar
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - gem install bundler && cd android && bundle install && cd ..
      script:
        - flutter packages get
        - flutter test
        - flutter build apk
        - cd android && bundle exec fastlane build_android && bundle exec fastlane deploy_android
