env:
  global:
    secure: aQC6rcTg3R9cYjSQjTJqJsJTHIp431IZklERqoDf4YfRmfv4lTe4fM/f+7PRJ8VuOnza0xI0H43HzRIgeL7/7ElY3vAygL9fdxNCNVtG6m69UBLjF93q10FrusKIRcMAhHiTZmxEDglMsU83syqK8EAIZ8NNyGEzx7ZOHr3zAyxVbtFCoGym+Ad+Fl39dEyB4wpTyG15dymBx1fYPz3Fmwg4eHCN/53JoW/b04A7HjkQKq4zKrZt1zx+t7jp6+4zpJNIFtgipWtPrnGyowP8kdL2ljc9S3MMAbniGEd6QkoFNyXJrZSoFJx8J+vYGa4dkgvaapClg9ISdO39r8fXONcIqUneQvipIJnv6SVOiTuve01cdEUQ3i1BbrPy8Z9Xr+9YDr6XrMI3DRedqmUPGDwhpk6UFYoGT8/cZogYWbmGe/bQoVvBtDu+rVwrMPXaiEvElzaMJA6QknuhY5jd5nF3BGOfts6M1LQOBAOGlILCG9yPITif+UJH926LRzZ6R8o76kAHxTDwR9097pYTlNMU20aNopk7kU6nj94fOLgubisJM3rF0CuW6DALcHTJBxnNc2up35pkaB/CstRBKOHWd1f7u082KmzQebmnkYsIObOXX3tzF2I7FzttoZqjgr1BnolfmS5HY8H1iKoeIvN2gET7ardV8nRmCYCge7o=

matrix:
  include:
    - name: Android Build
      language: android
      jdk: openjdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_script:
        - echo $decryption_password | gpg --passphrase-fd 0 secrets.tar.gpg
        - tar xvf secrets.tar
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - gem install bundler && cd android && bundle install && cd ..
      script:
        - flutter packages get
        - flutter test
        - flutter build apk
        - cd android && bundle exec fastlane build_android && bundle exec fastlane deploy_android
