# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test", flavor: "development", flags: "-Ptarget=lib/main_development.dart")
  end

  desc "Submit a new Alpha Build to Playstore Alpha Channel"
  lane :alpha do
    gradle(task: "clean bundleProductionRelease", flags: "-Ptarget=lib/main_production.dart")
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/productionRelease/app-production-release.aab",
      track: 'alpha',
      skip_upload_metadata: true
    )

  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build a development version"
  lane :builddev do
    gradle(task: "clean assembleDevelopmentRelease", flags: "-Ptarget=lib/main_development.dart")
  end
end
