# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :build_android do |options|
    sh "./flutter_test.sh"

    sh "./flutter_build.sh --clean #{300 + number_of_commits()}"
  end

  desc "Submit a new Build to selected Playstore Channel"
  lane :deploy_android do |options|
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/productionRelease/app-production-release.aab",
      track:  options[:production] ? 'production' : options[:internal] ? 'internal' : options[:beta] ? 'beta' : 'alpha',
      skip_upload_metadata: true
    )
  end
end
